const SHOW_SUCCESS_MESSAGE = 'SHOW_SUCCESS_MESSAGE';
const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export { SHOW_SUCCESS_MESSAGE, SHOW_ERROR_MESSAGE, CLEAR_MESSAGES };
